export const FETCH_ALL_CAMPUSES = "FETCH_ALL_CAMPUSES";
export const FETCH_CAMPUS = "FETCH_CAMPUS";
export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const FETCH_STUDENT = "FETCH_STUDENT";